image: "python:3.7.5"

stages:
  - lint
  - testing
  - deploy

lint:
  stage: lint
  variables:
    FLAKE8_MAX_LINE_LENGTH: 80
    FLAKE8_IGNORE: E302,W503

  before_script:
  - pip install flake8

  script:
    - flake8 . --max-line-length=$FLAKE8_MAX_LINE_LENGTH --ignore=$FLAKE8_IGNORE

test:
  stage: testing

  before_script: 
    - pip install git+https://$MZMLRIPPER_USER:$MZMLRIPPER_PW@gitlab.com/croningroup/origins/mzmlripper.git@master
    - pip install matplotlib
    - pip install numpy
    - pip uninstall pymongo
    - pip uninstall bson
    - pip install pytest
    - pip install bson
    - pip install pymongo
    - pip install coverage
    - pip install memory_profiler
    - pip install pandas

  script:
    - coverage run -m pytest tests -m unit -rf -x

pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - pip install sphinx_rtd_theme
  - sphinx-build -b html documentation/source public
  artifacts:
    paths:
    - public
